import toast from 'react-hot-toast';

// ---------- Utility: sanitize text for PDF ----------
const sanitizeTextForPDF = (text) => {
  if (!text) return '';
  return text
    .toString()
    .normalize('NFKD')                    // normalize Unicode
    .replace(/[\x00-\x1F\x7F-\x9F]/g, '') // remove control chars
    .replace(/[^\x20-\x7E\u00A0-\uFFFF]/g, '') // remove unsupported Unicode
    .replace(/\s+/g, ' ')                 // normalize whitespace
    .trim();
};

// ---------- JSON Export ----------
export const exportJSON = (history, analytics, language) => {
  const sanitizedHistory = history.map(item => ({
    question: sanitizeTextForPDF(item.question),
    answer: sanitizeTextForPDF(item.answer),
    feedback: sanitizeTextForPDF(item.feedback),
    duration: item.duration,
    performanceScore: item.performanceScore,
    confidenceLevel: item.confidenceLevel ?? analytics.confidenceLevel,
    emotionalTone: sanitizeTextForPDF(item.emotionalTone)
  }));

  const data = {
    interviewData: sanitizedHistory,
    analytics: {
      overallScore: analytics.overallScore,
      averageConfidence: analytics.confidenceLevel,
      totalDuration: analytics.totalDuration,
      emotionalAnalysis: sanitizeTextForPDF(analytics.emotionalTone),
      insights: sanitizeTextForPDF(analytics.insights)
    },
    metadata: {
      exportDate: new Date().toISOString(),
      totalQuestions: sanitizedHistory.length,
      language,
      sessionId: generateSessionId(),
      version: '2.0.0'
    }
  };

  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `smart-interview-${new Date().toISOString().split('T')[0]}.json`;
  a.click();
  toast.success('🚀 JSON exported with sanitized data!');
};

// ---------- PDF Export ----------
export const exportPDF = async (history, analytics) => {
  try {
    const { jsPDF } = await import('jspdf');
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPos = 20;

    // --------- HEADER ----------
    const addHeader = () => {
      doc.setFillColor(41, 98, 255);
      doc.rect(0, 0, pageWidth, 50, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('AI-Powered Interview Report', pageWidth / 2, 25, { align: 'center' });
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Generated by Smart Interview Assistant', pageWidth / 2, 35, { align: 'center' });
      yPos = 60;
    };

    // --------- PERFORMANCE SUMMARY ----------
    const addPerformanceSummary = () => {
      doc.setFillColor(245, 247, 250);
      doc.rect(20, yPos, pageWidth - 40, 40, 'F');
      doc.setTextColor(41, 98, 255);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Performance Summary', 25, yPos + 15);
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Overall Score: ${analytics.overallScore}%`, 25, yPos + 25);
      doc.text(`Confidence Level: ${analytics.confidenceLevel}%`, 25, yPos + 32);
      doc.text(`Emotional Tone: ${sanitizeTextForPDF(analytics.emotionalTone)}`, 25, yPos + 39);
      yPos += 55;
    };

    // --------- SUMMARY TABLE ----------
    const addSummaryTable = () => {
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      doc.text('Questions Summary', 25, yPos);
      yPos += 6;

      const colWidths = [20, 30, 30, 50]; // Q#, Score, Confidence, Tone
      const startX = 25;

      // Table header
      const headers = ['Q#', 'Score', 'Confidence', 'Emotional Tone'];
      let x = startX;
      headers.forEach((h, i) => {
        doc.text(h, x + 2, yPos);
        x += colWidths[i];
      });
      yPos += 5;

      // Table rows
      doc.setFont('helvetica', 'normal');
      history.forEach((item, index) => {
        let x = startX;
        const row = [
          (index + 1).toString(),
          `${item.performanceScore}%`,
          `${item.confidenceLevel ?? analytics.confidenceLevel}%`,
          sanitizeTextForPDF(item.emotionalTone)
        ];
        row.forEach((cell, i) => {
          doc.text(cell, x + 2, yPos);
          x += colWidths[i];
        });
        yPos += 5;
        if (yPos > pageHeight - 20) {
          doc.addPage();
          yPos = 20;
        }
      });
      yPos += 10;
    };

    // --------- QUESTION BLOCK ----------
    const addQuestionBlock = (item, index) => {
      const blockHeightEstimate = 70;
      if (yPos + blockHeightEstimate > pageHeight - 20) {
        doc.addPage();
        yPos = 20;
      }

      // Question
      doc.setFillColor(41, 98, 255);
      doc.rect(20, yPos, pageWidth - 40, 8, 'F');
      doc.setFontSize(10);
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.text(`🎯 Q${index + 1}: ${sanitizeTextForPDF(item.question)}`, 25, yPos + 5);
      yPos += 15;

      // Answer
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'normal');
      const answerLines = doc.splitTextToSize(`💬 ${sanitizeTextForPDF(item.answer)}`, pageWidth - 45);
      doc.text(answerLines, 25, yPos);
      yPos += answerLines.length * 5 + 8;

      // Metrics
      doc.setTextColor(102, 102, 102);
      doc.setFontSize(8);
      doc.text(`⏱️ ${item.duration}s | 📊 Score: ${item.performanceScore}% | 😊 ${sanitizeTextForPDF(item.emotionalTone)}`, 25, yPos);
      yPos += 6;

      // Feedback
      doc.setTextColor(41, 98, 255);
      doc.setFontSize(9);
      const feedbackLines = doc.splitTextToSize(`💡 ${sanitizeTextForPDF(item.feedback)}`, pageWidth - 45);
      doc.text(feedbackLines, 25, yPos);
      yPos += feedbackLines.length * 5 + 15;
    };

    // ---------- GENERATE PDF ----------
    addHeader();
    addPerformanceSummary();
    addSummaryTable();
    history.forEach((item, i) => addQuestionBlock(item, i));

    doc.save(`premium-interview-report-${new Date().toISOString().split('T')[0]}.pdf`);
    toast.success('📄 Premium PDF report (sanitized) generated!');
  } catch (error) {
    toast.error('❌ Failed to export PDF');
    console.error('PDF export error:', error);
  }
};

// ---------- SESSION ID ----------
export const generateSessionId = () => {
  return `session_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
};
